name: Deploy & Test Pull Request on Dev

on:
  pull_request:
    branches:
      - "*" # all branches
jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
    - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."  
    - name: Set variables
      id: setvars
      run: echo "STAGE=\"dev\"" >> $GITHUB_ENV
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - name: Copy environment variables to .env
      run: echo "${{ vars.ENV }}" >> .env
    - name: serverless deploy
      uses: serverless/github-action@v3.2
      with:
        args: deploy --stage ${{ env.STAGE }}
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    - run: echo "The eagle has landed! 🦅"
  newman:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - uses: actions/checkout@master
      - uses: matt-ball/newman-action@master
        with:
          apiKey: ${{ secrets.POSTMAN_API_KEY }}
          collection: ${{ secrets.POSTMAN_COLLECTION_ID }}
          environment: ${{ secrets.POSTMAN_DEV_ENV }}