name: Deploy & Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*" # all branches
jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
    - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."  
    - name: Set variables
      id: setvars
      run: |
        if [[ "${{github.ref}}" == "refs/heads/main" ]]; then
          echo "STAGE=\"prod\"" >> $GITHUB_ENV
        else
          echo "STAGE=\"dev\"" >> $GITHUB_ENV
        fi
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - name: Copy environment variables to .env
      run: echo "${{ vars.ENV }}" >> .env
    - name: serverless deploy
      uses: serverless/github-action@v3.2
      with:
        args: deploy --stage ${{ env.STAGE }}
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  newman:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: Set variables
        id: setvars
        run: |
          if [[ "${{github.ref}}" == "refs/heads/main" ]]; then
            echo "POSTMAN_ENVIRONMENT=\"${{ secrets.POSTMAN_PROD_ENV }}\"" >> $GITHUB_ENV
          else
            echo "POSTMAN_ENVIRONMENT=\"${{ secrets.POSTMAN_DEV_ENV }}\"" >> $GITHUB_ENV
          fi
      - uses: actions/checkout@master
      - uses: matt-ball/newman-action@master
        with:
          apiKey: ${{ secrets.POSTMAN_API_KEY }}
          collection: ${{ secrets.POSTMAN_COLLECTION_ID }}
          environment: |
            if [[ "${{github.ref}}" == "refs/heads/main" ]]; then
              echo "${{ secrets.POSTMAN_PROD_ENV }}"
            else
              echo "${{ secrets.POSTMAN_DEV_ENV }}"
            fi